### ISSUE TITLE
All Errors Fixed

### ISSUE THREAD

**Issue by Cold-Breazy** [hackerxphantom/Spoof_AnyMail#4]
I saw a majority of people who needed this tool to work but the developer decided to not to reply or at least update the tool so I have decided to do it for him. Anyway I have created the very similar code  to send emails here is the updated Tool : https://github.com/Cold-Breazy/Spoofmailer

**Comment by anonym0usgirl** [comment]
### **whenever i run python3 spoofy.py , this error occurs:-**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python' instead of 'python3'
python is already the newest version (3.12.7).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.12/site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests) (2020.6.20)
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Spoofmailer/spoofer.py", line 17, in <module>
    request = requests.get("https://www.google.com/search?q=freemailsender.com", timeout=3)
              ^^^^^^^^
NameError: name 'requests' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Spoofmailer/spoofer.py", line 18, in <module>
    except (requests.ConnectionError, requests.Timeout) as exception:
            ^^^^^^^^
NameError: name 'requests' is not defined

**Comment by anonym0usgirl** [comment]
any solution please
